name: ayur_care
description: "An Ayurvedic Patient Management App"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_svg: ^2.2.1
  http: ^1.5.0
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0




flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-100.ttf
        - asset: assets/fonts/Poppins_200.ttf
        - asset: assets/fonts/Poppins300.ttf
        - asset: assets/fonts/Poppins_400.ttf
        - asset: assets/fonts/Poppins_500.ttf
        - asset: assets/fonts/Poppins_600.ttf
        - asset: assets/fonts/Poppins_700.ttf
        - asset: assets/fonts/Poppins_800.ttf
        - asset: assets/fonts/Poppins_900.ttf